// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY8APMIs_itljOTCTDY2t8Nghi0rvoUMc',
    appId: '1:147607725699:web:b76b5c17ca822aebb3ddb6',
    messagingSenderId: '147607725699',
    projectId: 'legal-desk-170397',
    authDomain: 'legal-desk-170397.firebaseapp.com',
    storageBucket: 'legal-desk-170397.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq0l4OA-4JiFicV2XZGJ_9bIuumvhTM_U',
    appId: '1:147607725699:android:a2385b6ab4a703c0b3ddb6',
    messagingSenderId: '147607725699',
    projectId: 'legal-desk-170397',
    storageBucket: 'legal-desk-170397.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY8APMIs_itljOTCTDY2t8Nghi0rvoUMc',
    appId: '1:147607725699:web:1641e70bec9c8eb6b3ddb6',
    messagingSenderId: '147607725699',
    projectId: 'legal-desk-170397',
    authDomain: 'legal-desk-170397.firebaseapp.com',
    storageBucket: 'legal-desk-170397.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnh28iAdGrVBPSGU27E6_-BvNviR_Lisg',
    appId: '1:147607725699:ios:092edf1f923a1ec5b3ddb6',
    messagingSenderId: '147607725699',
    projectId: 'legal-desk-170397',
    storageBucket: 'legal-desk-170397.firebasestorage.app',
    iosBundleId: 'com.example.legalDesk',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnh28iAdGrVBPSGU27E6_-BvNviR_Lisg',
    appId: '1:147607725699:ios:cb461a23ece4fec3b3ddb6',
    messagingSenderId: '147607725699',
    projectId: 'legal-desk-170397',
    storageBucket: 'legal-desk-170397.firebasestorage.app',
    iosBundleId: 'com.madhav.legal-desk',
  );
}
